Convert to new style mkdocs
networktocode/netutils pull request #152
Opened 2022-10-10 19:56 UTC by itdependsnetworks

2022-10-11 16:03 UTC, jeffkala commented
should `code_references` be nested under `/docs/dev` or just `/docs`?

2022-10-11 16:06 UTC, itdependsnetworks commented
> should `code_references` be nested under `/docs/dev` or just `/docs`?

This is the standard already, I just followed it.

2022-10-11 16:16 UTC, jeffkala requested changes

2022-10-11 16:16 UTC, jeffkala commented on README.md
> +You can find all the Markdown source for the library documentation under the [docs](https://github.com/networktocode/netutils/tree/develop/docs) folder in this repository. For simple edits, a Markdow
```suggestion
All the Markdown source for the library documentation can be found under the [docs](https://github.com/networktocode/netutils/tree/develop/docs) folder in this repository. For simple edits, a Markdown capable editor is sufficient - clone the repository and edit away.
```

2022-10-11 16:16 UTC, jeffkala commented on docs/dev/dev_config.md
> +    - The class's `__init__` method must keep true to the signature or `__init__(self, config)`.
```suggestion
    - The classes `__init__` method must keep true to the signature or `__init__(self, config)`.
```

2022-10-11 16:16 UTC, jeffkala commented on docs/dev/dev_environment.md
> +1. `Recommended` All services are spun up using Docker and a local mount so you can develop locally, but Nautobot is spun up within the Docker container.
```suggestion
1. `Recommended` All services are spun up using Docker and a local mount so you can develop locally, but Netutils is spun up within the Docker container.
```

2022-10-11 16:16 UTC, jeffkala commented on docs/dev/dev_environment.md
> +The Nautobot server can now be accessed at [http://localhost:8080](http://localhost:8080) and the live documentation at [http://localhost:8001](http://localhost:8001).
```suggestion
Live documentation can be viewed at [http://localhost:8001](http://localhost:8001).
```

2022-10-11 16:16 UTC, jeffkala commented on docs/dev/dev_environment.md
> +Poetry is used in lieu of the "virtualenv" commands and is leveraged in both environments. The virtual environment will provide all of the Python packages required to manage the development environme
```suggestion
Poetry is used in lieu of the "virtualenv" commands and is leveraged in both environments. The virtual environment will provide all of the Python packages required to manage the development environment such as **Invoke**. See the [Local Development Environment](#local-poetry-development-environment) section to see how to install Netutils if you're going to be developing locally (i.e. not using the Docker container).
```

2022-10-12 14:06 UTC, qduk commented
I may just be missing it, but I don't see the functions for each file. Something equivalent to [this](https://netutils.readthedocs.io/en/latest/netutils/bandwidth/index.html)

2022-10-12 14:08 UTC, itdependsnetworks commented
> I may just be missing it, but I don't see the functions for each file. Something equivalent to [this](https://netutils.readthedocs.io/en/latest/netutils/bandwidth/index.html)

https://github.com/networktocode/netutils/pull/152/files#diff-34ec211d37292b70f8207ed7f4785ca06077f5ae7d67f5e8549ec5b4e47f20a0R5

2022-10-12 14:15 UTC, qduk approved these changes
LGTM

2022-10-12 14:17 UTC, merged