fix classfull address naming
networktocode/netutils pull request #173
Opened 2022-11-12 09:40 UTC by vivekvashist

2022-11-14 14:27 UTC, abates commented
I think if we're being pedantic, it should be `classful` with only one "l", see [here](https://learningnetwork.cisco.com/s/article/fundamentals-of-classful-ipv4-addressing)

2022-11-14 19:45 UTC, vivekvashist commented
> I think if we're being pedantic, it should be `classful` with only one "l", see [here](https://learningnetwork.cisco.com/s/article/fundamentals-of-classful-ipv4-addressing)

Ah, that is technically correct - If you want I can update this RR and resubmit.

2022-11-15 14:21 UTC, jeffkala requested changes

2022-11-15 14:21 UTC, jeffkala commented on netutils/ip.py
> +    """Determines if a CIDR network address is within unicast classfull boundaries.
```suggestion
    """Determines if a CIDR network address is within unicast classful boundaries.
```

2022-11-15 14:21 UTC, jeffkala commented on netutils/ip.py
> +        Whether or not the network falls within classfull boundaries.
```suggestion
        Whether or not the network falls within classful boundaries.
```

2022-11-15 14:21 UTC, jeffkala commented on netutils/ip.py
> +    # Only IPv4 addresses can be classified as classfull
```suggestion
    # Only IPv4 addresses can be classified as classful
```

2022-11-15 14:52 UTC, abates commented on netutils/ip.py
>  def is_classfull(ip_network: str) -> bool:  # noqa: D300,D301
```suggestion
def is_classful(ip_network: str) -> bool:  # noqa: D300,D301
```

2022-11-15 14:54 UTC, abates commented
> Ah, that is technically correct - If you want I can update this RR and resubmit.

Since you already have a PR going those changes would be great. I still can't believe I spelled it wrong in the first place 🤦

2022-11-15 22:20 UTC, vivekvashist commented
Apologies, I got my branching messed up and accidentally created a new PR :(

2022-11-16 17:40 UTC, vivekvashist commented
Done.

2022-11-30 00:24 UTC, vivekvashist commented
Not sure if this was closed by accident but the following changes are are still pending 

https://github.com/networktocode/netutils/pull/173/commits/91c777d663de655cca87ab53ef19abdd521786fe

2022-11-30 12:33 UTC, abates commented
@vivekvashist we got confused with the other PR and thought these changes had already been merged.

2022-11-30 13:43 UTC, abates commented
@vivekvashist can you please fix this PR so that the tests pass?

2022-11-30 22:49 UTC, vivekvashist commented
```
(netutils-py3.10) ~/D/netutils ❯❯❯ pytest -k test_docs_generated --no-header                                              ✘ 4 develop
======================================================== test session starts ========================================================
collected 438 items / 437 deselected / 1 selected

tests/unit/test_docs.py::test_docs_generated PASSED                                                                           [100%]

================================================= 1 passed, 437 deselected in 1.89s =================================================
(netutils-py3.10) ~/D/netutils ❯❯❯
```

2022-12-08 17:27 UTC, abates approved these changes

2022-12-16 02:05 UTC, itdependsnetworks approved these changes

2022-12-16 02:05 UTC, merged