Docs contribution update
networktocode/netutils pull request #71
Opened 2021-11-12 22:33 UTC by qduk

2021-11-12 22:42 UTC, jeffkala requested changes

2021-11-12 22:42 UTC, jeffkala commented on README.md
> +- Docstrings must conform to the google docstring standard.
```suggestion
- Docstrings must conform to the google docstring [convention](https://google.github.io/styleguide/pyguide.html#381-docstrings).
```

2021-11-12 22:42 UTC, jeffkala commented on tests/unit/test_docs.py
>          "start_value": "Pull requests are welcomed and automatically built and tested against multiple versions of Python through TravisCI.\n",
```suggestion
        "start_value": "Pull requests are welcomed and automatically built and tested against multiple versions of Python through GitHub Actions.\n",
```

2021-11-12 22:44 UTC, itdependsnetworks commented on README.md
> +- Update the jinja2 filter for any new functions.
Can you explain this a bit more?

2021-11-12 22:44 UTC, itdependsnetworks commented on README.md
> +- Update the jinja2 filter for any new functions.
nvm, can you just add a `(see below for details)` to the end of the doc

2021-11-13 01:31 UTC, itdependsnetworks approved these changes

2021-11-13 15:34 UTC, merged